# Postgres Database
development:
  adapter: postgresql
  database: smart_garden_dev
  pool: 10

test:
  adapter: postgresql
  database: smart_garden_test
  pool: 10

production:
  adapter: postgresql
  database: smart_garden_prod
  pool: 5
